languageCode: de-CH
languageName: Deutsch
weight: 10
title: Übermittlungsdienst (UemD)

params:
  displayName: Deutsch
  isoCode: de
  description: Daten sicher übermittelt - Verbindung um jeden Preis!
  keywords:
    - UemD
    - Übermittlungsdienst
    - Dokumentenspeicher
    - Schweiz
    - Zürich
    - Zürich-Oerlikon
    - Oerlikon
  author:
    image: img/uemd-icon-512x512.png
    name: Übermittlungsdienst
    headline: Verbindung um jeden Preis!
    links:
      - email: mailto:info@uemd.ch
