languageCode: en-GB
languageName: English
weight: 20
title: Transfer service

params:
  displayName: English
  isoCode: en
  description: Data securely transferred – connection at all costs!
  keywords:
    - UemD
    - Transfer service
    - Document storage
    - Switzerland
    - Zurich
    - Zurich-Oerlikon
    - Oerlikon
  author:
    image: img/uemd-icon-512x512.png
    name: Transfer service
    headline: Connection at all costs!
    links:
      - email: mailto:info@uemd.ch
