main:
  - name: Über uns
    pageRef: /about-us
    weight: 10
  - name: Dienstleistungen
    pageRef: /services
    weight: 20

footer:
  - name: Impressum
    pageRef: /legal-notice
    weight: 10
  - name: Datenschutzerklärung
    pageRef: /privacy-statement
    weight: 20
