main:
  - name: About
    pageRef: /about
    weight: 10
  - name: Services
    pageRef: /services
    weight: 20

footer:
  - name: Legal notice
    pageRef: /legal-notice
    weight: 10
  - name: Privacy statement
    pageRef: /privacy-statement
    weight: 20
